name: example
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  flutter_icons_generator: ^1.0.0-dev
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: FirstIcons
      fonts:
        - asset: ./assets/icon_fonts/first_icons.otf
